# LiteLLM Proxy 配置 - 阶段0 内网生产 (启用 Llama-Guard-3)

model_list:
  # 1. 主推理模型
  - model_name: qwen3
    litellm_params:
      model: openai/qwen3.8-27b
      #api_base: http://172.21.0.1:8000/v1
      api_base: http://172.25.0.10:8001/v1
      api_type: openai
      api_key: "EMPTY"
    model_info:
      max_tokens: 16384

  # 2. Embedding 模型
  - model_name: qwen3-embedding
    litellm_params:
      model: openai/qwen3-embedding
      api_base: http://172.29.0.165:8000/v1
      api_type: openai
      api_key: "EMPTY"
    model_info:
      description: "本地部署的Embed Text 模型"
      supports_embedding: true 

general_settings:
  #embedding_model: nomic-embed-text
  disable_key_management: true
  return_openai_object: true
  #disable_spend_logs: true
  #store_model_in_db: false

# 语义缓存（Redis DB 0）
litellm_settings:
  cache: true  # set cache responses to True, litellm defaults to using a redis cache
  cache_params:
    #type: "redis"
    type: "redis-semantic"
    similarity_threshold: 0.8   # similarity threshold for semantic cache
    redis_semantic_cache_embedding_model: qwen3-embedding

    # Redis cache parameters
    host: redis-cache  # Redis server hostname or IP address
    port: "6379"  # Redis server port (as a string)
    password: magedu.com  # Redis server password    

# 日志
logging:
  level: DEBUG
  log_file: /app/logs/litellm.log
